# Generated by Django 3.0.3 on 2020-06-18 17:40

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_product'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cartproducts',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
